apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster-a
        appProject: default
        k8sURL: https://kubernetes.default.svc
        gitRepoURL: https://github.com/sungwook-practice/argocd-rbac-test.git
        path: apps/cluster-a
        targetRevision: HEAD
  template:
    metadata:
      name: '{{cluster}}-apps'
    spec:
      project: '{{appProject}}'
      source:
        repoURL: '{{gitRepoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: '{{k8sURL}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
