apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstraps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster-a
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-bootstrap'
    spec:
      project: default
      source:
        repoURL: https://github.com/sungwook-practice/argocd-rbac-test.git
        targetRevision: HEAD
        path: bootstrap/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
